### ISSUE TITLE
Move 404Assets into Assets + Create Sitemap

### ISSUE THREAD

**Issue by HydroCodez** [Hydrovolter/Portfolio#3]
Move ./404Assets into /assets to keep main (github) page and index cleaner. Maybe also move 404.html into another folder. Minimise index page.

Also create a Sitemap for Google SEO.

**Comment by Deveroonie** [comment]
do that then

**Comment by Hydrovolter** [comment]
When I get time

**Comment by HydroCodez** [comment]
fr no time too busy.

BUT i have moved the 404Assets into Assets

just need to create a sitemap
